const data = [
  {
    "data": "2025-10-02",
    "dzien": "Czwartek",
    "start": "08:00",
    "end": "11:00",
    "przedmiot": "Procedury przedszpitalne z kwalifikowanym kursem pierwszej pomocy",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-02",
    "dzien": "Czwartek",
    "start": "12:00",
    "end": "13:30",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-02",
    "dzien": "Czwartek",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Biofizyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-02",
    "dzien": "Czwartek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Badanie fizykalne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-02",
    "dzien": "Czwartek",
    "start": "17:30",
    "end": "19:00",
    "przedmiot": "Anatomia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+8h e-learning"
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "08:00",
    "end": "09:30",
    "przedmiot": "Mikrobiologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "09:45",
    "end": "11:15",
    "przedmiot": "Biologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "11:30",
    "end": "13:00",
    "przedmiot": "Zdrowie publiczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "13:30",
    "end": "15:00",
    "przedmiot": "Podstawowe zabiegi medyczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "15:15",
    "end": "16:45",
    "przedmiot": "Psychologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-03",
    "dzien": "Piątek",
    "start": "17:00",
    "end": "20:00",
    "przedmiot": "Etyka zawodowa ratownika medycznego",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-06",
    "dzien": "Poniedziałek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-06",
    "dzien": "Poniedziałek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Anatomia",
    "miejsce": "Międzywydziałowe Centrum Dydaktyki nr 1, al. Powstańców Wlkp. 72",
    "sala": "10",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-06",
    "dzien": "Poniedziałek",
    "start": "17:45",
    "end": "20:00",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-07",
    "dzien": "Wtorek",
    "start": "10:30",
    "end": "12:45",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-07",
    "dzien": "Wtorek",
    "start": "16:00",
    "end": "17:30",
    "przedmiot": "Dydaktyka medyczna",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-07",
    "dzien": "Wtorek",
    "start": "17:45",
    "end": "20:45",
    "przedmiot": "Etyka zawodowa ratownika medycznego",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-08",
    "dzien": "Środa",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Dydaktyka medyczna",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-09",
    "dzien": "Czwartek",
    "start": "08:00",
    "end": "11:00",
    "przedmiot": "Procedury przedszpitalne z kwalifikowanym kursem pierwszej pomocy",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-09",
    "dzien": "Czwartek",
    "start": "12:00",
    "end": "13:30",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-09",
    "dzien": "Czwartek",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Biochemia z elementami chemii",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+6h e-learning"
  },
  {
    "data": "2025-10-09",
    "dzien": "Czwartek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Badanie fizykalne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-09",
    "dzien": "Czwartek",
    "start": "17:30",
    "end": "19:00",
    "przedmiot": "Biofizyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-10",
    "dzien": "Piątek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Mikrobiologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-10",
    "dzien": "Piątek",
    "start": "10:30",
    "end": "12:45",
    "przedmiot": "Biologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-10",
    "dzien": "Piątek",
    "start": "13:30",
    "end": "15:00",
    "przedmiot": "Podstawowe zabiegi medyczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-10",
    "dzien": "Piątek",
    "start": "15:15",
    "end": "16:45",
    "przedmiot": "Psychologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-10",
    "dzien": "Piątek",
    "start": "17:00",
    "end": "18:30",
    "przedmiot": "Dydaktyka medyczna",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-13",
    "dzien": "Poniedziałek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-13",
    "dzien": "Poniedziałek",
    "start": "13:00",
    "end": "15:15",
    "przedmiot": "Mikrobiologia",
    "miejsce": "Zakład Medycyny Laboratoryjnej, al. Powstańców Wlkp. 72",
    "sala": "",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-13",
    "dzien": "Poniedziałek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Anatomia",
    "miejsce": "Międzywydziałowe Centrum Dydaktyki nr 1, al. Powstańców Wlkp. 72",
    "sala": "10",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-13",
    "dzien": "Poniedziałek",
    "start": "17:45",
    "end": "20:00",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-14",
    "dzien": "Wtorek",
    "start": "10:30",
    "end": "12:45",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-14",
    "dzien": "Wtorek",
    "start": "16:00",
    "end": "17:30",
    "przedmiot": "Dydaktyka medyczna",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-14",
    "dzien": "Wtorek",
    "start": "17:45",
    "end": "19:15",
    "przedmiot": "Etyka zawodowa ratownika medycznego",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-15",
    "dzien": "Środa",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Dydaktyka medyczna",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-16",
    "dzien": "Czwartek",
    "start": "08:00",
    "end": "11:00",
    "przedmiot": "Procedury przedszpitalne z kwalifikowanym kursem pierwszej pomocy",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-16",
    "dzien": "Czwartek",
    "start": "12:00",
    "end": "13:30",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-16",
    "dzien": "Czwartek",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Biochemia z elementami chemii",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+6h e-learning"
  },
  {
    "data": "2025-10-16",
    "dzien": "Czwartek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Badanie fizykalne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-16",
    "dzien": "Czwartek",
    "start": "17:30",
    "end": "19:00",
    "przedmiot": "Biofizyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-17",
    "dzien": "Piątek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Informatyka i biostatystyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-17",
    "dzien": "Piątek",
    "start": "11:30",
    "end": "13:00",
    "przedmiot": "Zdrowie publiczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-17",
    "dzien": "Piątek",
    "start": "13:30",
    "end": "15:00",
    "przedmiot": "Podstawowe zabiegi medyczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-17",
    "dzien": "Piątek",
    "start": "15:15",
    "end": "16:45",
    "przedmiot": "Psychologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-17",
    "dzien": "Piątek",
    "start": "18:30",
    "end": "20:45",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-20",
    "dzien": "Poniedziałek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-20",
    "dzien": "Poniedziałek",
    "start": "13:00",
    "end": "15:15",
    "przedmiot": "Mikrobiologia",
    "miejsce": "Zakład Medycyny Laboratoryjnej, al. Powstańców Wlkp. 72",
    "sala": "",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-20",
    "dzien": "Poniedziałek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Anatomia",
    "miejsce": "Międzywydziałowe Centrum Dydaktyki nr 1, al. Powstańców Wlkp. 72",
    "sala": "10",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-20",
    "dzien": "Poniedziałek",
    "start": "17:45",
    "end": "20:00",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-21",
    "dzien": "Wtorek",
    "start": "10:30",
    "end": "12:45",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-21",
    "dzien": "Wtorek",
    "start": "16:00",
    "end": "19:45",
    "przedmiot": "Biofizyka",
    "miejsce": "Zakład Fizyki Medycznej, ul. Ku Słońcu 13",
    "sala": "2",
    "grupa": "S1",
    "forma": "Seminaria",
    "uwagi": ""
  },
  {
    "data": "2025-10-22",
    "dzien": "Środa",
    "start": "15:00",
    "end": "17:15",
    "przedmiot": "Wprowadzenie do symulacji",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "A",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-22",
    "dzien": "Środa",
    "start": "15:00",
    "end": "17:15",
    "przedmiot": "Wprowadzenie do symulacji",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "B",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-23",
    "dzien": "Czwartek",
    "start": "08:00",
    "end": "11:00",
    "przedmiot": "Procedury przedszpitalne z kwalifikowanym kursem pierwszej pomocy",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-23",
    "dzien": "Czwartek",
    "start": "12:00",
    "end": "13:30",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-23",
    "dzien": "Czwartek",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Biochemia z elementami chemii",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+6h e-learning"
  },
  {
    "data": "2025-10-23",
    "dzien": "Czwartek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Badanie fizykalne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-23",
    "dzien": "Czwartek",
    "start": "17:30",
    "end": "19:00",
    "przedmiot": "Biofizyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "08:00",
    "end": "09:30",
    "przedmiot": "Informatyka i biostatystyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "09:45",
    "end": "11:15",
    "przedmiot": "Prawo medyczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+8h e-learning"
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "11:30",
    "end": "13:00",
    "przedmiot": "Zdrowie publiczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "13:30",
    "end": "15:00",
    "przedmiot": "Podstawowe zabiegi medyczne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "15:15",
    "end": "16:45",
    "przedmiot": "Psychologia",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-24",
    "dzien": "Piątek",
    "start": "18:30",
    "end": "20:45",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-27",
    "dzien": "Poniedziałek",
    "start": "08:00",
    "end": "10:15",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-27",
    "dzien": "Poniedziałek",
    "start": "13:00",
    "end": "15:15",
    "przedmiot": "Mikrobiologia",
    "miejsce": "Zakład Medycyny Laboratoryjnej, al. Powstańców Wlkp. 72",
    "sala": "",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-27",
    "dzien": "Poniedziałek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Anatomia",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-27",
    "dzien": "Poniedziałek",
    "start": "17:45",
    "end": "20:00",
    "przedmiot": "Język obcy",
    "miejsce": "SPNJO, ul. Ku Słońcu 12 (wejście od Sikorskiego)",
    "sala": "",
    "grupa": "JW1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-28",
    "dzien": "Wtorek",
    "start": "10:30",
    "end": "12:45",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Wydział Nauk o Zdrowiu, ul. Żołnierska 48",
    "sala": "2",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-28",
    "dzien": "Wtorek",
    "start": "15:00",
    "end": "16:30",
    "przedmiot": "Anatomia",
    "miejsce": "Międzywydziałowe Centrum Dydaktyki nr 1, al. Powstańców Wlkp. 72",
    "sala": "10",
    "grupa": "1",
    "forma": "Ćwiczenia",
    "uwagi": ""
  },
  {
    "data": "2025-10-28",
    "dzien": "Wtorek",
    "start": "19:00",
    "end": "20:30",
    "przedmiot": "Biochemia z elementami chemii",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-30",
    "dzien": "Czwartek",
    "start": "08:00",
    "end": "11:00",
    "przedmiot": "Procedury przedszpitalne z kwalifikowanym kursem pierwszej pomocy",
    "miejsce": "Centrum Symulacji Medycznej, ul. Sebastiana Klonowica 50",
    "sala": "?",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-30",
    "dzien": "Czwartek",
    "start": "12:00",
    "end": "13:30",
    "przedmiot": "Fizjologia z elementami fizjologii klinicznej",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-30",
    "dzien": "Czwartek",
    "start": "13:45",
    "end": "15:15",
    "przedmiot": "Biochemia z elementami chemii",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": "+6h e-learning"
  },
  {
    "data": "2025-10-30",
    "dzien": "Czwartek",
    "start": "15:45",
    "end": "17:15",
    "przedmiot": "Badanie fizykalne",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  },
  {
    "data": "2025-10-30",
    "dzien": "Czwartek",
    "start": "17:30",
    "end": "19:00",
    "przedmiot": "Biofizyka",
    "miejsce": "Online",
    "sala": "",
    "grupa": "Cały rok",
    "forma": "Wykład",
    "uwagi": ""
  }
];
